
# model configuration
model:
    arch: unet
    n_classes: 3
    in_channels: 3
    depth: 5
    n_start_filters: 64
    filter_num_scale: 2
    up_mode: transpose  # or upsample
    merge_mode: concat  # or add

data:
    dataset: drive
    path: ../datasets/  # the path to where the DRIVE folder is located
training:
    n_workers: 4
    n_epochs: 50
    batch_size: 4
    loss:
        name: combined_loss # cross_entropy , dice_loss,
                            # create the weight tensor in train.py

    optimizer:
        name: adam  # sgd
        lr: 0.001

    augmentations: #
        hflip: 0.5
        rotate: 90

#    lr_scheduler:
#        name: step_lr
#        step_size: 10
#        gamma: 0.05
